import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./sidebar/Sidebar";
import Navbar from "./navBar/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* Sidebar */}
        {/* <Sidebar/> */}
        <div style={{ height: "200px" }}>
          <Navbar />
        </div>
        <main style={{ flex: 1, padding: "20px" }}>{children}</main>
      </body>
    </html>
  );
}
